/* bus.c - see bus.h.  Targets SOEM 2.0 (context-based ecx_* API). */
#include "bus.h"
#include "soem/soem.h"
#include <stdio.h>

static ecx_contextt ctx;   /* the one master context for this process */

int bus_open(const char *ifname)
{
    if (!ecx_init(&ctx, ifname)) {
        fprintf(stderr, "bus: ecx_init('%s') failed - check NIC name and permissions "
                        "(run as root or setcap cap_net_raw,cap_net_admin+ep)\n", ifname);
        return -1;
    }
    int n = ecx_config_init(&ctx);   /* requests PRE-OP; no PDO map needed for SDO */
    if (n <= 0) {
        fprintf(stderr, "bus: no slaves found on '%s'\n", ifname);
        ecx_close(&ctx);
        return 0;
    }
    /* The mailbox (SDO) only works in PRE-OP or higher. Force PRE-OP on the whole
     * bus, verify, and if a slave refuses, print its AL status code (which says why). */
    ctx.slavelist[0].state = EC_STATE_PRE_OP;
    ecx_writestate(&ctx, 0);
    ecx_statecheck(&ctx, 0, EC_STATE_PRE_OP, EC_TIMEOUTSTATE);
    ecx_readstate(&ctx);
    for (int i = 1; i <= ctx.slavecount; i++) {
        if (ctx.slavelist[i].state != EC_STATE_PRE_OP) {
            fprintf(stderr,
                    "bus: slave %d did not reach PRE-OP (state=0x%02X, AL status=0x%04X: %s)\n",
                    i, (unsigned)ctx.slavelist[i].state, (unsigned)ctx.slavelist[i].ALstatuscode,
                    ec_ALstatuscode2string(ctx.slavelist[i].ALstatuscode));
        }
    }
    return n;
}

void bus_close(void) { ecx_close(&ctx); }

void bus_print_slaves(void)
{
    printf("%d slave(s) found:\n", ctx.slavecount);
    for (int i = 1; i <= ctx.slavecount; i++) {
        ec_slavet *s = &ctx.slavelist[i];
        printf("  [%d] %-20s vendor=0x%08X product=0x%08X rev=0x%08X  state=0x%02X\n",
               i, s->name, (unsigned)s->eep_man, (unsigned)s->eep_id,
               (unsigned)s->eep_rev, (unsigned)s->state);
    }
}

int sdo_read(uint16_t s, uint16_t idx, uint8_t sub, void *buf, int size)
{
    int sz = size;
    int wkc = ecx_SDOread(&ctx, s, idx, sub, FALSE, &sz, buf, EC_TIMEOUTRXM);
    return wkc > 0;
}

int sdo_write(uint16_t s, uint16_t idx, uint8_t sub, const void *buf, int size)
{
    int wkc = ecx_SDOwrite(&ctx, s, idx, sub, FALSE, size, (void *)buf, EC_TIMEOUTRXM);
    return wkc > 0;
}

/* --- cyclic process data / OP --- */
static uint8 IOmap[256];   /* drive needs 16 out + 39 in; plenty of room */

void bus_report_state(const char *what)
{
    ecx_readstate(&ctx);
    fprintf(stderr, "bus: %s (state=0x%02X AL=0x%04X: %s)\n", what,
            (unsigned)ctx.slavelist[1].state, (unsigned)ctx.slavelist[1].ALstatuscode,
            ec_ALstatuscode2string(ctx.slavelist[1].ALstatuscode));
}

int bus_enter_op(void)
{
    if (ecx_config_map_group(&ctx, IOmap, 0) <= 0) {
        fprintf(stderr, "bus: config_map failed\n");
        return 0;
    }
    ecx_statecheck(&ctx, 0, EC_STATE_SAFE_OP, EC_TIMEOUTSTATE);
    if (ctx.slavelist[0].state != EC_STATE_SAFE_OP) {
        bus_report_state("did not reach SAFE-OP");
        return 0;
    }
    /* This drive's native mode is DC: activate SYNC0 (generated by the slave's own
     * clock hardware) so it gets the sync pulse it needs to hold OP. 2 ms cycle. */
    ecx_configdc(&ctx);
    ecx_dcsync0(&ctx, 1, TRUE, 2000000, 0);

    /* OP needs live process data: prime one frame, request OP, keep cycling. */
    ecx_send_processdata(&ctx);
    ecx_receive_processdata(&ctx, EC_TIMEOUTRET);
    ctx.slavelist[0].state = EC_STATE_OPERATIONAL;
    ecx_writestate(&ctx, 0);
    for (int i = 0; i < 200 && ctx.slavelist[0].state != EC_STATE_OPERATIONAL; i++) {
        ecx_send_processdata(&ctx);
        ecx_receive_processdata(&ctx, EC_TIMEOUTRET);
        ecx_statecheck(&ctx, 0, EC_STATE_OPERATIONAL, 50000);
    }
    if (ctx.slavelist[0].state != EC_STATE_OPERATIONAL) {
        bus_report_state("failed to reach OP");
        return 0;
    }
    return 1;
}

void bus_cycle(void)
{
    ecx_send_processdata(&ctx);
    ecx_receive_processdata(&ctx, EC_TIMEOUTRET);
}

void bus_debug(void)
{
    ecx_send_processdata(&ctx);
    int wkc = ecx_receive_processdata(&ctx, EC_TIMEOUTRET);
    ec_slavet *s = &ctx.slavelist[1];
    int exp = ctx.grouplist[0].outputsWKC * 2 + ctx.grouplist[0].inputsWKC;
    printf("io: wkc=%d (expected %d)  Obytes=%u Ibytes=%u  inputs:",
           wkc, exp, (unsigned)s->Obytes, (unsigned)s->Ibytes);
    for (uint32 i = 0; i < s->Ibytes && i < 16; i++) printf(" %02X", s->inputs[i]);
    printf("\n");
}

void bus_set_controlword(uint16_t cw)
{
    uint8 *o = ctx.slavelist[1].outputs;
    if (o) { o[0] = (uint8)cw; o[1] = (uint8)(cw >> 8); }   /* 6040h @ offset 0 */
}

void bus_set_mode(int8_t mode)
{
    uint8 *o = ctx.slavelist[1].outputs;
    if (o) o[10] = (uint8)mode;                             /* 6060h @ offset 10 */
}

void bus_set_target_velocity(int32_t v)
{
    uint8 *o = ctx.slavelist[1].outputs;
    if (o) { o[6] = (uint8)v; o[7] = (uint8)(v >> 8);       /* 60FFh @ offset 6 */
             o[8] = (uint8)(v >> 16); o[9] = (uint8)(v >> 24); }
}

void bus_set_target_position(int32_t p)
{
    uint8 *o = ctx.slavelist[1].outputs;
    if (o) { o[2] = (uint8)p; o[3] = (uint8)(p >> 8);       /* 607Ah @ offset 2 */
             o[4] = (uint8)(p >> 16); o[5] = (uint8)(p >> 24); }
}

uint16_t bus_statusword(void)
{
    const uint8 *in = ctx.slavelist[1].inputs;
    /* Firmware's real TxPDO starts with StatusWord at offset 0 (the ESI's 39-byte
     * 0x1A00 with a leading ErrorCode does NOT match this drive - verified by 'pdomap'). */
    return in ? (uint16_t)(in[0] | (in[1] << 8)) : 0;
}

int32_t bus_velocity_actual(void)
{
    const uint8 *in = ctx.slavelist[1].inputs;             /* 606Ch @ offset 6 */
    if (!in) return 0;
    return (int32_t)((uint32_t)in[6] | ((uint32_t)in[7] << 8) |
                     ((uint32_t)in[8] << 16) | ((uint32_t)in[9] << 24));
}

int32_t bus_position_actual(void)
{
    const uint8 *in = ctx.slavelist[1].inputs;             /* 6064h @ offset 2 */
    if (!in) return 0;
    return (int32_t)((uint32_t)in[2] | ((uint32_t)in[3] << 8) |
                     ((uint32_t)in[4] << 16) | ((uint32_t)in[5] << 24));
}
